/**
 * 關於茗強 — transcribed from the existing site (page/1/關於茗強).
 * Six numbered sections plus the founder profile.
 */
export const about = {
  establishment: {
    index: "01",
    title: "成立緣由",
    titleEn: "Establishment",
    acronym: "MCREAFM",
    paragraphs: [
      "本企業負責人蘇又德與團隊內主要人員具有不動產估價師、都市計畫技師、地政士、不動產經紀人、不動產經紀營業員、企業評價師、信託業務人員、期貨商業務員或投信投顧等專業證照，可提供客戶全方位「地政與土管（LAND ECONOMICS & LAND MANAGEMENT）」事務之專業服務，包含不動產估價、城鄉規劃（含「非都市土地開發許可及變更編定」、「都市計畫擬定、通檢及變更」等）、不動產經紀、不動產登記、不動產稅務諮詢、不動產理財規劃、動產鑑價、無形資產評價、企業評價等。",
      "為於「地政與土管」事務上建立一個重視團隊、遵守法紀、誠信正直、樂於分享、積極進取、奉行公義之企業，並使企業全體成員具有策劃（MASTERMIND）合作、負責專注（CONCENTRATION）、關係（REALATIONSHIP）和諧、胸懷熱忱（ENTHUSIASTIC）、正確（ACCURATE）思維、充滿信心（FAITH）的工作態度，使客戶享有如品佳茗、回甘力強之服務，本企業負責人乃依前述信念，自民國103年起陸續成立茗強地政士事務所（MING CHIANG REAL ESTATE ATTORNEY FIRM）、茗強不動產估價師事務所（MING CHIANG REAL ESTATE ATTORNEY FIRM）、茗強資產鑑定有限公司（MING CHIANG ASSET IDENTIFICATION LTD.）、茗強都市計畫技師事務所（MING CHIANG URBAN PLANNING ENGINEERING FIRM）、茗強不動產經紀有限公司（MING CHIANG REAL ESTATE LTD.）。",
      "藉由「茗強地政與土管（MING CHIANG LAND ECONOMICS & LAND MANAGEMENT）」專業團隊，提供客戶全方位「地政與土管」事務之專業服務。",
    ],
    photo: { src: "/images/about/office.webp", alt: "團隊會議", width: 400, height: 265 },
    valuesImage: { src: "/images/about/values-logo.webp", alt: "茗強識別：M互助、C認真、R可靠、E熱忱、A精確、F清新", width: 1000, height: 997 },
    wheelImage: { src: "/images/about/services-wheel.png", alt: "專業服務：不動產估價、城鄉規劃、不動產經紀、不動產登記相關、動產鑑價相關", width: 1000, height: 989 },
  },
  philosophy: {
    index: "02",
    title: "經營理念",
    titleEn: "Business Philosophy",
    lead: "以誠信為基石，進而以誠感人",
    paragraphs: [
      "本企業負責人出生於1979年，該年台灣相繼發生米糠油中毒、假酒事件，進而引發中華民國消費者文教基金會等民間消費者保護團體興起。時至今日，台灣食品安全問題事件仍層出不窮，不僅影響消費者的健康安全，打擊食品相關產業和國家聲譽，亦危害社會信任。",
      "一般來說，食品加工有其必要性，但食物若過度加工，不但使人忘了食物最根本、原始、感人的味道，也會對身體健康產生負面的影響；過度加工的食品，或許初見時外觀誘人、初聞時氣味迷人、初嚐時滋味動人，但細細品味後，味道終究難以感人。",
      "另本企業負責人於創業前曾服務過之三家公司或事務所之名稱有一共同特色，即其名稱皆有一「信」字。孔子曾說：「民無信不立。」亦曾說：「人而無信，不知其可也。」於該三家公司或事務所服務之歷程中，本企業負責人深感誠信乃是人格的基石，言行一致，口心相同，乃是為人處事應有的基本態度。",
      "北宋學者程頤曾說：「以誠感人者，人亦誠而應。」良好服務過程予人之感受，就如同品佳茗過程予人醇厚甘潤、口感清爽、香氣自然、回甘力強之感受；好的茶葉，不僅外觀誘人、氣味引人、滋味動人，細細品味後，味道還能感人。",
      "因此，在以誠信為基石之前提下，為在本業提供在地化、差異化及客製化之可靠服務，進而以誠感人，使客戶在被服務之過程中體驗到「如品佳茗，回甘力強」之感受，本企業負責人乃將所創立之公司或事務所取名為「茗強」，藉由「茗強地政與土管」專業服務團隊，提供客戶方位「地政與土管」事務之專業服務。",
    ],
  },
  purpose: {
    index: "03",
    title: "立業宗旨",
    titleEn: "Founding Purpose",
    lead: "提供客戶如品佳茗、回甘力強之服務",
    text: "培養同仁重視團隊、積極進取、樂於分享之從業態度，並追求企業奉行公義、遵守法紀、誠信正直之發展願景，進而提供客戶如品佳茗、回甘力強之服務。",
    attitudeImage: { src: "/images/about/attitude.png", alt: "MCREAF：重視團隊、策劃合作、遵守法紀、負責專注、關係和諧、誠信正直、樂於分享、胸懷熱忱、正確思維、積極進取、充滿信心、奉行公義", width: 1304, height: 674 },
    teaImage: { src: "/images/about/tea.png", alt: "如品佳茗 回甘力強 Ming Chiang", width: 1081, height: 514 },
  },
  events: {
    index: "04",
    title: "重大記事",
    titleEn: "Event",
    /** Transcribed from the existing site's timeline graphic. */
    timeline: [
      { year: "2014", roc: "103年11月", title: "成立茗強地政士事務所" },
      { year: "2015", roc: "104年12月", title: "成立茗強不動產估價師事務所" },
      { year: "2016", roc: "105年10月", title: "成立茗強資產鑑定有限公司" },
      { year: "2017", roc: "106年11月", title: "成立茗強不動產估價師聯合事務所" },
      { year: "2019", roc: "108年03月", title: "與「逢甲大學地理資訊系統中心」合作", text: "開始共同參與公部門用地取得採購案，已有諸多成功經驗", muted: true },
      { year: "2020", roc: "109年11月", title: "成立茗強都市計畫技師事務所" },
      { year: "2020", roc: "109年12月", title: "當選臺中市政府108年度優良不動產估價師", text: "「茗強地政與土管」負責人蘇又德獲得此項殊榮", muted: true },
      { year: "2023", roc: "112年06月", title: "取得博士學位", text: "本企業負責人蘇又德取得逢甲大學建設規劃與工程博士學位", muted: true },
      { year: "2024", roc: "113年04月", title: "成立茗強不動產經紀有限公司", text: "加盟惠双房屋，為惠双房屋台中茗強加盟店" },
      { year: "2024", roc: "113年11月", title: "創立十週年", text: "茗強地政與土管創立十週年" },
    ],
    image: { src: "/images/about/timeline.png", alt: "茗強地政與土管重大記事時間軸", width: 2402, height: 1598 },
  },
  organization: {
    index: "05",
    title: "組織架構",
    titleEn: "Organization",
    paragraphs: [
      "「茗強地政與土管」專業團隊內計有「茗強不動產估價師事務所」、「茗強都市計畫技師事務所」、「茗強不動產經紀有限公司」、「茗強地政士事務所」、「茗強資產鑑定有限公司」及人資行政處、財務處、數位學習部、廣告暨策略行銷部等部門，計有地政、土地管理、城鄉規劃、都市更新、不動產經紀、不動產登記、資產鑑定、資訊等領域之20餘名工作人員。",
      "有關「茗強地政與土管」之組織架構如下圖所示。",
    ],
    image: { src: "/images/about/org-chart.webp", alt: "茗強地政與土管組織架構圖", width: 1800, height: 1054 },
  },
  team: {
    index: "06",
    title: "專業團隊",
    titleEn: "Professional Team",
    founder: {
      role: "茗強地政與土管負責人",
      name: "蘇又德",
      photo: { src: "/images/about/founder.webp", alt: "蘇又德", width: 609, height: 783 },
      education: ["逢甲大學建設規劃與工程博士", "逢甲大學都市計畫與空間資訊學系碩士", "成功大學航空太空工程學系", "臺中一中"],
      current: [
        "茗強不動產估價師事務所所長",
        "茗強都市計畫技師事務所所長",
        "茗強不動產經紀有限公司負責人",
        "茗強地政士事務所所長",
        "茗強資產鑑定有限公司負責人",
        "台中市不動產估價師公會第八屆常務監事",
        "中華民國不動產估價師公會全國聯合會第七屆理事",
        "中華民國不動產估價師公會全國聯合會第七屆研究發展委員會暨不動產估價研究發展經費委員會委員",
        "臺中市政府教育局學校財團法人及所設私立學校不動產處分案件審查小組委員",
        "苗栗縣政府都市計畫委員會委員",
        "彰化縣地價及標準地價評議委員會委員",
        "彰化縣地價基準地專案小組委員",
        "南投縣地價及標準地價評議委員會委員",
        "南投縣地價基準地選定及查估審議專案小組委員",
        "南投縣不動產評價委員會委員",
      ],
      awards: ["臺中市政府108年度優良不動產估價師"],
      awardImages: [
        { src: "/images/about/award-1.png", alt: "臺中市政府108年度優良不動產估價師 頒獎", width: 900, height: 657 },
        { src: "/images/about/award-2.webp", alt: "臺中市政府108年度優良不動產估價師 獎牌", width: 450, height: 342 },
      ],
      experience: [
        "信義房屋不動產經紀營業員",
        "華信不動產估價師聯合事務所鑑價部副理",
        "中國信託商業銀行理財規劃部經理",
        "茗強不動產估價師聯合事務所所長",
        "台中市不動產估價師公會第五屆副秘書長",
        "台中市不動產估價師公會第六屆常務理事暨會務發展委員會主任委員",
        "台中市不動產估價師公會第七屆副理事長暨教育委員會主任委員",
        "中華民國不動產估價師公會全國聯合會第五屆、第六屆理事",
        "中華民國不動產估價師公會全國聯合會第五屆都市更新事務委員會暨法制委員會委員",
        "中華民國不動產估價師公會全國聯合會第六屆專業推廣委員會副主任委員暨估價專案委員會委員",
        "南投縣政府都市計畫委員會委員",
        "南投縣政府國土計畫審議委員會委員",
        "南投縣非都市土地使用分區及使用地變更申請審查小組委員會委員",
        "南投縣政府都市更新及爭議處理審議委員會委員",
        "臺中市都市更新及產業發展學會理事",
      ],
      licenses: ["不動產估價師考試及格證書", "都市計畫計師證書", "地政士考試及格證書", "不動產經紀人證書", "企業評價師證書（中華無形資產暨企業評價協會認證）"],
      publications: [
        "A study on the valuation of brownfield regeneration with consideration of sustainable use（2024 International Conference on Land Sustainability and Real Estate Management，國際研討會，113年03月）",
        "The appraisal pattern based on real option valuation model a case study of the appraisal of compensation for alteration in Taiwan. (31st Pan Pacific Congress of Real Estate Appraiser, Valuers and Counsellors，國際研討會，112年09月）",
        "The appraisal patterns of privately-owned social housing projects based on real option valuation model. (31st Pan Pacific Congress of Real Estate Appraiser, Valuers and Counsellors，國際研討會，112年09月）",
        "基於實質選擇權評價法之變更補償費、更新後土地及建築物與社會住宅估價模型（逢甲大學建設規劃與工程博士論文、112年07月）",
        "我國之容積移轉制度、各縣市以折繳代金方式於接受基地移入容積之實施現況及相關建議（台中市地政士公會會刊、第35期、112年3月）",
        "Valuation of compensation for land use restriction, Asian Journal of Economics, Business and Accounting (AJEBA)（國際期刊投稿，112年2月）",
        "實施國土計畫管制後所受損失之變更補償費估價方法探討（台中市地政士公會會刊、第34期、111年3月）",
        "實施國土計畫管制後所受損失之變更補償費查估作業方式探討（台中市地政士公會成立三十週年特刊、110年12月）",
        "Pricing strategies of land and buildings after urban renewal with real option-based valuation model：A case study of Taichung city, Taiwan, International Journal of Economics, Business and Management Research (IJEBMR)（國際期刊投稿，110年5月）",
        "Pricing strategies of privately-owned social housing projects：A case study of Taichung city, Taiwan, International Journal of Economics, Business and Management Research (IJEBMR)（國際期刊投稿，110年3月）",
        "The Impact of Agricultural Science and Technology Innovation on the Development of Agricultural Information System（APFITA2019、國際研討會、108年10月）",
        "限制發展地區損失補償之研究──以國土計畫法第32條為中心（逢甲大學都市計畫與空間資訊學系碩士論文、107年06月）",
        "都市更新價值評定之研究──以權利變換實施方式中之土地改良物拆遷補償費為例（城事話-都市計畫與空間資訊研討會、第五屆、107年5月5日）",
        "國土計畫功能分區劃設原則探討──以國土保育地區為例（城事話-都市計畫與空間資訊研討會、第五屆、107年5月5日）",
        "從採礦場經營業者之角度探討礦場資源價值評估之研究（城事話-都市計畫與空間資訊研討會、第五屆、107年5月5日）",
        "前瞻基礎建設計畫內容之探討—以軌道建設計畫內容為主（台中市地政士公會會刊、第31期、107年3月）",
        "論述國土計畫法第三十二條觀點之限制發展地區損失補償之研究（城事話-都市計畫與空間資訊研討會、第四屆、106年4月29日）",
        "都市設計管制對於城鎮風貌型塑之影響—以安平港歷史風貌園區周邊為例（台中市地政士公會會刊、第30期、106年3月）",
        "依「看見台灣」紀錄片探討土地利用之失衡狀況（台中市地政士公會會刊、第29期、105年3月）",
      ],
    },
  },
} as const;

export const careers = {
  title: "人才招募",
  photo: { src: "/images/pages/careers.webp", alt: "團隊合作", width: 736, height: 550 },
  positions: [
    "一、誠徵合夥不動產估價師、不動產估價助理員、不動產估價師助理數名。",
    "二、誠徵都市計畫技師、城鄉規劃助理數名。",
    "三、誠徵不動產經紀人、不動產經紀營業員數名。",
    "四、誠徵地政士、地政士登記助理員、地政士助理數名。",
    "五、誠徵無形資產評價師、企業評價師、評價人員數名。",
  ],
  text: "「茗強地政與土管」定期舉辦專業教育訓練，培訓同仁考取不動產估價師、都市計畫技師、不動產經紀人、不動產經紀營業員、地政士、企業評價師或無形資產評價師等專業證照。若您想於工作中學得不動產估價、城鄉規劃、不動產經紀、地政相關登記事務、動產鑑價、無形資產評價或企業評價等專業知識，歡迎您加入「茗強地政與土管」的行列。",
} as const;

export const contactInfo = {
  parking: {
    title: "停車資訊",
    text: "本公司及事務所周邊有數座停車場，另於本公司及事務所西北側之梅川綠園道兩側亦設有收費停車格，欲前來本公司及事務所時可善加利用。以下為推薦之停車場位置資訊：",
    lots: [
      { name: "民五停車場：", text: "為位於本公司及事務所東南側約10公尺處之私人收費停車場。" },
      { name: "Times停車場：", text: "為位於本公司及事務所東北側約60公尺處之私人收費停車場。" },
    ],
  },
  map: { src: "/images/contact/map.webp", alt: "本公司及事務所位置地圖", width: 810, height: 592 },
} as const;
